android.useAndroidX=true
android.enableJetifier=true

//# Increase heap size to 2 GB (adjust if needed)
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8

//# Optional: stop logging this warning
org.gradle.daemon.performance.disable-logging=true

//org.gradle.parallel=true
//org.gradle.configureondemand=true